services:
  backend:
    build: ./backend
    ports:
      - "5001:5001" 
    networks:
      - mern  
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  
    networks:
      - mern

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern 
    volumes:
      - mongo-data:/data/db  

networks:
  mern:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally